spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8082/realms/digital-house
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: gateway
            client-secret: 8ApRuWZ9sAgN99e9LjklkTWkCBNhNrJi
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
server:
  port: 9090